# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 672c3ac4f03ebad5a55aeacc09e41500faa75adad4485b23c4d1dadc106dc7cc8c20b6ad5a27d062e6f8faab4825e02b5ccb1c9ece36aa9b75bfc15b6614abdb

test:
  secret_key_base: 3485c60097d34e5fc895ee898ce50457d2400ce31f8d84b84d61eda7e898b774faca6771cb068224bd8613e8924dfa495294fed9179544bce79af3fc17660584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
